import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button, Stack } from "@mui/material";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Stack
        flexDirection={"column"}
        justifyContent={"center"}
        alignItems={"center"}
        minHeight={"100vh"}
        gap={3}
      >
        <Button variant='contained' onClick={() => router.push("/select")}>
          UI 1
        </Button>
        <Button variant='contained' onClick={() => router.push("/qrcode")}>
          UI 2
        </Button>
        <Button variant='contained' onClick={() => router.push("/chill")}>
          UI 3
        </Button>
      </Stack>
    </>
  );
}
